name: Test
on: [push]
jobs:
  something:
    name: Something
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4
      - name: run terraform init
        run: |
            cd module-13 && terraform init
      - uses: env0/terratag-action@v2
        with:
          tags: |
            {
              "env0_environment_id":"40907eff-cf7c-419a-8694-e1c6bf1d1168","env0_project_id":"43fd4ff1-8d37-4d9d-ac97-295bd850bf94"
            }
          dir: module-13 
          
      - name: check
        run: |
            cd module-13/publish_bucket
            cat bucket-and-something.terratag.tf
